#!/bin/tcsh
#PBS -l mem=8gb,nodes=1:ppn=1,walltime=30:00:00
#PBS -o /gsfs0/data/[author_blinded]/gbu/outs/out_file_hmm
#PBS -e /gsfs0/data/[author_blinded]/gbu/outs/error_file_hmm
module load anaconda/2019.10-p3.7
cd /gsfs0/data/[author_blinded]/gbu/src/python
python train.py -a hmm -s $1 -f $2   -o > /gsfs0/data/[author_blinded]/gbu/outs/hmm$1$2.txt
