#!/bin/tcsh
#PBS -l mem=6gb,nodes=1:ppn=1,walltime=12:00:00
#PBS -o /gsfs0/data/[author_blinded]/gbu/outs/out_file_rf
#PBS -e /gsfs0/data/[author_blinded]/gbu/outs/error_file_rf
module load anaconda/2019.10-p3.7
cd /gsfs0/data/[author_blinded]/gbu/src/python
python train.py -a rf -f $1 -o  -d $2 -e $3> /gsfs0/data/[author_blinded]/gbu/outs/rf_$1$2$3.txt