#!/bin/tcsh
#PBS -l mem=6gb,nodes=1:ppn=1,walltime=24:00:00
#PBS -o /gsfs0/data/[author_blinded]/gbu/outs/out_file_sahoo
#PBS -e /gsfs0/data/[author_blinded]/gbu/outs/error_file_sahoo
module load anaconda/2019.10-p3.7
cd /gsfs0/data/[author_blinded]/gbu/src/python
python train_sahoo.py  -s $1 -f $2 -o > /gsfs0/data/[author_blinded]/gbu/outs/sahoo_$1$2.txt
