#!/bin/tcsh
#PBS -l mem=6gb,nodes=1:ppn=1,walltime=08:00:00
#PBS -o /gsfs0/data/[author_blinded]/gbu/outs/out_file
#PBS -e /gsfs0/data/[author_blinded]/gbu/outs/error_file
module load anaconda/2019.10-p3.7
cd /gsfs0/data/[author_blinded]/gbu/src/python
python train.py -a xg -f $1 -o -d $2 -e $3 -S $4 > /gsfs0/data/[author_blinded]/gbu/outs/xg_$1$2$3$4.txt